"""Student roster export — masked-Aadhaar workbook.

Ported from the notebook's "Download ALL STUDENTS DETAILS" cell. Aadhaar is
masked here exactly as the notebook does; no unmasked value is written.
"""

from __future__ import annotations

import re
import time

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

ALL_COLUMNS = [
    "S. No.", "Class", "Section", "Student Name",
    "Mother Name", "Father Name", "PEN Number",
    "Date of Birth", "Mobile No.", "Masked Aadhaar", "APAAR ID",
]
ALL_COL_WIDTHS = [8, 10, 10, 26, 24, 24, 18, 16, 16, 20, 22]


def mask_aadhaar(value) -> str:
    if not value:
        return "N/A"
    raw = re.sub(r"\D", "", str(value))
    if len(raw) >= 4:
        return f"XXXX-XXXX-{raw[-4:]}"
    return str(value) if str(value).strip() else "N/A"


def get_apaar_id(student: dict) -> str:
    for key in ("apaarId", "apaarNo", "aparId", "studentApaarId",
                "apaar_id", "apaarNumber"):
        val = student.get(key)
        if val is not None and str(val).strip() not in ("", "0", "None", "null"):
            return str(val).strip()
    return "N/A"


def export_students(session, path: str) -> str:
    """Fetch each student's profile and write the details workbook."""
    if not session.students:
        raise RuntimeError("Roster is not loaded. Run login first.")

    wb = Workbook()
    ws = wb.active
    ws.title = "ALL STUDENTS DETAILS"
    ws.row_dimensions[1].height = 32

    fill_hdr = PatternFill("solid", fgColor="1F4E79")
    font_hdr = Font(bold=True, color="FFFFFF", size=10)
    font_norm = Font(color="000000", size=10)
    align_ctr = Alignment(horizontal="center", vertical="center")
    align_left = Alignment(horizontal="left", vertical="center")
    thin = Side(style="thin", color="CCCCCC")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    for ci, hdr in enumerate(ALL_COLUMNS, 1):
        c = ws.cell(1, ci, hdr)
        c.font = font_hdr
        c.fill = fill_hdr
        c.alignment = align_ctr
        c.border = border

    for ci, width in enumerate(ALL_COL_WIDTHS, 1):
        ws.column_dimensions[get_column_letter(ci)].width = width

    ws.freeze_panes = "G2"

    total = len(session.students)
    written = 0
    print(f"Fetching details for {total} students…", flush=True)

    for student in session.students:
        sid = str(student.get("studentId") or student.get("id") or "").strip()
        pen = str(student.get("studentCodeNat") or "").strip()
        try:
            detail = session.student_detail(sid)
        except Exception:
            continue

        row = written + 2
        ws.cell(row, 1, written + 1).alignment = align_ctr
        ws.cell(row, 2, detail.get("classDesc", "")).alignment = align_ctr
        ws.cell(row, 3, detail.get("sectionDesc", "")).alignment = align_ctr
        ws.cell(row, 4, detail.get("studentName", "")).alignment = align_left
        ws.cell(row, 5, detail.get("motherName", "")).alignment = align_left
        ws.cell(row, 6, detail.get("fatherName", "")).alignment = align_left
        ws.cell(row, 7, detail.get("studentCodeNat", "") or pen).alignment = align_ctr
        ws.cell(row, 8, detail.get("dob", "")).alignment = align_ctr
        ws.cell(row, 9, detail.get("primaryMobile", "") or "N/A").alignment = align_ctr
        ws.cell(row, 10, mask_aadhaar(detail.get("uuid"))).alignment = align_ctr
        ws.cell(row, 11, get_apaar_id(detail)).alignment = align_ctr

        for ci in range(1, 12):
            c = ws.cell(row, ci)
            c.border = border
            c.font = font_norm

        written += 1
        if written % 25 == 0 or written == total:
            print(f"  {written}/{total} written…", flush=True)
        time.sleep(0.05)

    footer = ws.cell(written + 3, 1,
                     f"Generated by UDISE+ VPS runner | School: {session.school_id}")
    footer.font = Font(color="C9A84C", italic=True, size=9)

    wb.save(path)
    print(f"✅ Exported {written} students → {path}", flush=True)
    return path
